# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python


python:
  - 3.5
  - 3.4
  - 2.7

install:
  - pip install -U pip pipenv
  - pipipenv install --dev

script:
  - python setup.py flake8
  - pipenv run pytest test

after_success:
  coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: Stibbons/txwebbackendbase
